---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: latest apache2 installed
    apt:
      name: apache2	
      state: latest
    notify:
      - restart apache2
  - name: create index.html file
    file:
      name: /var/www/html/index.html
      state: touch
  - name: add web content
    lineinfile:
      line: "{{ ansible_hostname }}"
      path: /var/www/html/index.html
    notify:
      - restart apache2
  - name: start apache2
    service:
      name: apache2
      state: started

  handlers:
    - name: Attempt to restart apache2
      service:
        name: apache2
        state: restarted
      listen: "restart apache2"

